//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGAIJE.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SGAIJEEntities : DbContext
    {
        public SGAIJEEntities()
            : base("name=SGAIJEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<prGetDetalleCotizacion_Result> prGetDetalleCotizacion(Nullable<System.Guid> unqCtzDetalleCotizacionKey, Nullable<System.Guid> unqCtzMastCotizacionLink)
        {
            var unqCtzDetalleCotizacionKeyParameter = unqCtzDetalleCotizacionKey.HasValue ?
                new ObjectParameter("unqCtzDetalleCotizacionKey", unqCtzDetalleCotizacionKey) :
                new ObjectParameter("unqCtzDetalleCotizacionKey", typeof(System.Guid));
    
            var unqCtzMastCotizacionLinkParameter = unqCtzMastCotizacionLink.HasValue ?
                new ObjectParameter("unqCtzMastCotizacionLink", unqCtzMastCotizacionLink) :
                new ObjectParameter("unqCtzMastCotizacionLink", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetDetalleCotizacion_Result>("prGetDetalleCotizacion", unqCtzDetalleCotizacionKeyParameter, unqCtzMastCotizacionLinkParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> prMantenimientoDetalleCotizacion(Nullable<System.Guid> unqCtzDetalleCotizacionKey, Nullable<System.Guid> unqCtzMastCotizacionLink, Nullable<System.Guid> unqGenArticuloLink, Nullable<int> intCantidad, Nullable<decimal> decValorUnitario, Nullable<decimal> decDescuento, Nullable<decimal> decMontoTotal, Nullable<int> intTop)
        {
            var unqCtzDetalleCotizacionKeyParameter = unqCtzDetalleCotizacionKey.HasValue ?
                new ObjectParameter("unqCtzDetalleCotizacionKey", unqCtzDetalleCotizacionKey) :
                new ObjectParameter("unqCtzDetalleCotizacionKey", typeof(System.Guid));
    
            var unqCtzMastCotizacionLinkParameter = unqCtzMastCotizacionLink.HasValue ?
                new ObjectParameter("unqCtzMastCotizacionLink", unqCtzMastCotizacionLink) :
                new ObjectParameter("unqCtzMastCotizacionLink", typeof(System.Guid));
    
            var unqGenArticuloLinkParameter = unqGenArticuloLink.HasValue ?
                new ObjectParameter("unqGenArticuloLink", unqGenArticuloLink) :
                new ObjectParameter("unqGenArticuloLink", typeof(System.Guid));
    
            var intCantidadParameter = intCantidad.HasValue ?
                new ObjectParameter("intCantidad", intCantidad) :
                new ObjectParameter("intCantidad", typeof(int));
    
            var decValorUnitarioParameter = decValorUnitario.HasValue ?
                new ObjectParameter("decValorUnitario", decValorUnitario) :
                new ObjectParameter("decValorUnitario", typeof(decimal));
    
            var decDescuentoParameter = decDescuento.HasValue ?
                new ObjectParameter("decDescuento", decDescuento) :
                new ObjectParameter("decDescuento", typeof(decimal));
    
            var decMontoTotalParameter = decMontoTotal.HasValue ?
                new ObjectParameter("decMontoTotal", decMontoTotal) :
                new ObjectParameter("decMontoTotal", typeof(decimal));
    
            var intTopParameter = intTop.HasValue ?
                new ObjectParameter("intTop", intTop) :
                new ObjectParameter("intTop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("prMantenimientoDetalleCotizacion", unqCtzDetalleCotizacionKeyParameter, unqCtzMastCotizacionLinkParameter, unqGenArticuloLinkParameter, intCantidadParameter, decValorUnitarioParameter, decDescuentoParameter, decMontoTotalParameter, intTopParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> prMantenimientoMastCotizacion(Nullable<System.Guid> unqCtzMastCotizacionKey, Nullable<System.Guid> unqGenClienteLink, Nullable<System.Guid> unqGenPlantillaLink, string vchComentarios, Nullable<System.DateTime> dtmFecha, string noFolio, Nullable<decimal> decImporteTotal, Nullable<bool> bitAceptada, Nullable<bool> bitIVA, Nullable<int> intTop)
        {
            var unqCtzMastCotizacionKeyParameter = unqCtzMastCotizacionKey.HasValue ?
                new ObjectParameter("unqCtzMastCotizacionKey", unqCtzMastCotizacionKey) :
                new ObjectParameter("unqCtzMastCotizacionKey", typeof(System.Guid));
    
            var unqGenClienteLinkParameter = unqGenClienteLink.HasValue ?
                new ObjectParameter("unqGenClienteLink", unqGenClienteLink) :
                new ObjectParameter("unqGenClienteLink", typeof(System.Guid));
    
            var unqGenPlantillaLinkParameter = unqGenPlantillaLink.HasValue ?
                new ObjectParameter("unqGenPlantillaLink", unqGenPlantillaLink) :
                new ObjectParameter("unqGenPlantillaLink", typeof(System.Guid));
    
            var vchComentariosParameter = vchComentarios != null ?
                new ObjectParameter("vchComentarios", vchComentarios) :
                new ObjectParameter("vchComentarios", typeof(string));
    
            var dtmFechaParameter = dtmFecha.HasValue ?
                new ObjectParameter("dtmFecha", dtmFecha) :
                new ObjectParameter("dtmFecha", typeof(System.DateTime));
    
            var noFolioParameter = noFolio != null ?
                new ObjectParameter("NoFolio", noFolio) :
                new ObjectParameter("NoFolio", typeof(string));
    
            var decImporteTotalParameter = decImporteTotal.HasValue ?
                new ObjectParameter("decImporteTotal", decImporteTotal) :
                new ObjectParameter("decImporteTotal", typeof(decimal));
    
            var bitAceptadaParameter = bitAceptada.HasValue ?
                new ObjectParameter("bitAceptada", bitAceptada) :
                new ObjectParameter("bitAceptada", typeof(bool));
    
            var bitIVAParameter = bitIVA.HasValue ?
                new ObjectParameter("bitIVA", bitIVA) :
                new ObjectParameter("bitIVA", typeof(bool));
    
            var intTopParameter = intTop.HasValue ?
                new ObjectParameter("intTop", intTop) :
                new ObjectParameter("intTop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("prMantenimientoMastCotizacion", unqCtzMastCotizacionKeyParameter, unqGenClienteLinkParameter, unqGenPlantillaLinkParameter, vchComentariosParameter, dtmFechaParameter, noFolioParameter, decImporteTotalParameter, bitAceptadaParameter, bitIVAParameter, intTopParameter);
        }
    
        public virtual ObjectResult<prGetArticulo_Result> prGetArticulo(Nullable<System.Guid> unqGenArticuloKey)
        {
            var unqGenArticuloKeyParameter = unqGenArticuloKey.HasValue ?
                new ObjectParameter("unqGenArticuloKey", unqGenArticuloKey) :
                new ObjectParameter("unqGenArticuloKey", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetArticulo_Result>("prGetArticulo", unqGenArticuloKeyParameter);
        }
    
        public virtual ObjectResult<prGetPlantilla_Result> prGetPlantilla(Nullable<System.Guid> unqGenPlantillaKey)
        {
            var unqGenPlantillaKeyParameter = unqGenPlantillaKey.HasValue ?
                new ObjectParameter("unqGenPlantillaKey", unqGenPlantillaKey) :
                new ObjectParameter("unqGenPlantillaKey", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetPlantilla_Result>("prGetPlantilla", unqGenPlantillaKeyParameter);
        }
    
        public virtual ObjectResult<prGetTipoArticulo_Result> prGetTipoArticulo(Nullable<System.Guid> unqGenTipoArticuloKey)
        {
            var unqGenTipoArticuloKeyParameter = unqGenTipoArticuloKey.HasValue ?
                new ObjectParameter("unqGenTipoArticuloKey", unqGenTipoArticuloKey) :
                new ObjectParameter("unqGenTipoArticuloKey", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetTipoArticulo_Result>("prGetTipoArticulo", unqGenTipoArticuloKeyParameter);
        }
    
        public virtual ObjectResult<prGetTipoCliente_Result> prGetTipoCliente(Nullable<System.Guid> unqGenTipoClienteKey)
        {
            var unqGenTipoClienteKeyParameter = unqGenTipoClienteKey.HasValue ?
                new ObjectParameter("unqGenTipoClienteKey", unqGenTipoClienteKey) :
                new ObjectParameter("unqGenTipoClienteKey", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetTipoCliente_Result>("prGetTipoCliente", unqGenTipoClienteKeyParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> prMantenimientoArticulo(Nullable<System.Guid> unqGenArticuloKey, Nullable<System.Guid> unqGenTipoArticuloLink, string vchCodigoArticulo, string vchDescripcion, Nullable<decimal> decPrecio, Nullable<decimal> decDescuento, Nullable<int> intExistencia, Nullable<int> intCantidadMaxima, Nullable<int> intCantidadMinima, Nullable<int> intTop)
        {
            var unqGenArticuloKeyParameter = unqGenArticuloKey.HasValue ?
                new ObjectParameter("unqGenArticuloKey", unqGenArticuloKey) :
                new ObjectParameter("unqGenArticuloKey", typeof(System.Guid));
    
            var unqGenTipoArticuloLinkParameter = unqGenTipoArticuloLink.HasValue ?
                new ObjectParameter("unqGenTipoArticuloLink", unqGenTipoArticuloLink) :
                new ObjectParameter("unqGenTipoArticuloLink", typeof(System.Guid));
    
            var vchCodigoArticuloParameter = vchCodigoArticulo != null ?
                new ObjectParameter("vchCodigoArticulo", vchCodigoArticulo) :
                new ObjectParameter("vchCodigoArticulo", typeof(string));
    
            var vchDescripcionParameter = vchDescripcion != null ?
                new ObjectParameter("vchDescripcion", vchDescripcion) :
                new ObjectParameter("vchDescripcion", typeof(string));
    
            var decPrecioParameter = decPrecio.HasValue ?
                new ObjectParameter("decPrecio", decPrecio) :
                new ObjectParameter("decPrecio", typeof(decimal));
    
            var decDescuentoParameter = decDescuento.HasValue ?
                new ObjectParameter("decDescuento", decDescuento) :
                new ObjectParameter("decDescuento", typeof(decimal));
    
            var intExistenciaParameter = intExistencia.HasValue ?
                new ObjectParameter("intExistencia", intExistencia) :
                new ObjectParameter("intExistencia", typeof(int));
    
            var intCantidadMaximaParameter = intCantidadMaxima.HasValue ?
                new ObjectParameter("intCantidadMaxima", intCantidadMaxima) :
                new ObjectParameter("intCantidadMaxima", typeof(int));
    
            var intCantidadMinimaParameter = intCantidadMinima.HasValue ?
                new ObjectParameter("intCantidadMinima", intCantidadMinima) :
                new ObjectParameter("intCantidadMinima", typeof(int));
    
            var intTopParameter = intTop.HasValue ?
                new ObjectParameter("intTop", intTop) :
                new ObjectParameter("intTop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("prMantenimientoArticulo", unqGenArticuloKeyParameter, unqGenTipoArticuloLinkParameter, vchCodigoArticuloParameter, vchDescripcionParameter, decPrecioParameter, decDescuentoParameter, intExistenciaParameter, intCantidadMaximaParameter, intCantidadMinimaParameter, intTopParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> prMantenimientoCliente(Nullable<System.Guid> unqGenClienteKey, Nullable<System.Guid> unqGenTipoClienteLink, string vchNombre, string vchApellidoP, string vchApellidoM, string vchRFC, string vchCalle, string vchNoExterior, string vchColonia, string vchCodigoPostal, string vchTelefono, string vchCorreo, Nullable<int> intTop)
        {
            var unqGenClienteKeyParameter = unqGenClienteKey.HasValue ?
                new ObjectParameter("unqGenClienteKey", unqGenClienteKey) :
                new ObjectParameter("unqGenClienteKey", typeof(System.Guid));
    
            var unqGenTipoClienteLinkParameter = unqGenTipoClienteLink.HasValue ?
                new ObjectParameter("unqGenTipoClienteLink", unqGenTipoClienteLink) :
                new ObjectParameter("unqGenTipoClienteLink", typeof(System.Guid));
    
            var vchNombreParameter = vchNombre != null ?
                new ObjectParameter("vchNombre", vchNombre) :
                new ObjectParameter("vchNombre", typeof(string));
    
            var vchApellidoPParameter = vchApellidoP != null ?
                new ObjectParameter("vchApellidoP", vchApellidoP) :
                new ObjectParameter("vchApellidoP", typeof(string));
    
            var vchApellidoMParameter = vchApellidoM != null ?
                new ObjectParameter("vchApellidoM", vchApellidoM) :
                new ObjectParameter("vchApellidoM", typeof(string));
    
            var vchRFCParameter = vchRFC != null ?
                new ObjectParameter("vchRFC", vchRFC) :
                new ObjectParameter("vchRFC", typeof(string));
    
            var vchCalleParameter = vchCalle != null ?
                new ObjectParameter("vchCalle", vchCalle) :
                new ObjectParameter("vchCalle", typeof(string));
    
            var vchNoExteriorParameter = vchNoExterior != null ?
                new ObjectParameter("vchNoExterior", vchNoExterior) :
                new ObjectParameter("vchNoExterior", typeof(string));
    
            var vchColoniaParameter = vchColonia != null ?
                new ObjectParameter("vchColonia", vchColonia) :
                new ObjectParameter("vchColonia", typeof(string));
    
            var vchCodigoPostalParameter = vchCodigoPostal != null ?
                new ObjectParameter("vchCodigoPostal", vchCodigoPostal) :
                new ObjectParameter("vchCodigoPostal", typeof(string));
    
            var vchTelefonoParameter = vchTelefono != null ?
                new ObjectParameter("vchTelefono", vchTelefono) :
                new ObjectParameter("vchTelefono", typeof(string));
    
            var vchCorreoParameter = vchCorreo != null ?
                new ObjectParameter("vchCorreo", vchCorreo) :
                new ObjectParameter("vchCorreo", typeof(string));
    
            var intTopParameter = intTop.HasValue ?
                new ObjectParameter("intTop", intTop) :
                new ObjectParameter("intTop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("prMantenimientoCliente", unqGenClienteKeyParameter, unqGenTipoClienteLinkParameter, vchNombreParameter, vchApellidoPParameter, vchApellidoMParameter, vchRFCParameter, vchCalleParameter, vchNoExteriorParameter, vchColoniaParameter, vchCodigoPostalParameter, vchTelefonoParameter, vchCorreoParameter, intTopParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> prMantenimientoPlantilla(Nullable<System.Guid> unqGenPlantillaKey, string vchDescripcion, string vchPathPlantilla, Nullable<int> intTop)
        {
            var unqGenPlantillaKeyParameter = unqGenPlantillaKey.HasValue ?
                new ObjectParameter("unqGenPlantillaKey", unqGenPlantillaKey) :
                new ObjectParameter("unqGenPlantillaKey", typeof(System.Guid));
    
            var vchDescripcionParameter = vchDescripcion != null ?
                new ObjectParameter("vchDescripcion", vchDescripcion) :
                new ObjectParameter("vchDescripcion", typeof(string));
    
            var vchPathPlantillaParameter = vchPathPlantilla != null ?
                new ObjectParameter("vchPathPlantilla", vchPathPlantilla) :
                new ObjectParameter("vchPathPlantilla", typeof(string));
    
            var intTopParameter = intTop.HasValue ?
                new ObjectParameter("intTop", intTop) :
                new ObjectParameter("intTop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("prMantenimientoPlantilla", unqGenPlantillaKeyParameter, vchDescripcionParameter, vchPathPlantillaParameter, intTopParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> prMantenimientoTipoArticulo(Nullable<System.Guid> unqGenTipoArticuloKey, string vchDescripcion, Nullable<int> intTop)
        {
            var unqGenTipoArticuloKeyParameter = unqGenTipoArticuloKey.HasValue ?
                new ObjectParameter("unqGenTipoArticuloKey", unqGenTipoArticuloKey) :
                new ObjectParameter("unqGenTipoArticuloKey", typeof(System.Guid));
    
            var vchDescripcionParameter = vchDescripcion != null ?
                new ObjectParameter("vchDescripcion", vchDescripcion) :
                new ObjectParameter("vchDescripcion", typeof(string));
    
            var intTopParameter = intTop.HasValue ?
                new ObjectParameter("intTop", intTop) :
                new ObjectParameter("intTop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("prMantenimientoTipoArticulo", unqGenTipoArticuloKeyParameter, vchDescripcionParameter, intTopParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> prMantenimientoTipoCliente(Nullable<System.Guid> unqGenTipoClienteKey, string vchDescripcion, Nullable<decimal> decDescuento, Nullable<int> intTop)
        {
            var unqGenTipoClienteKeyParameter = unqGenTipoClienteKey.HasValue ?
                new ObjectParameter("unqGenTipoClienteKey", unqGenTipoClienteKey) :
                new ObjectParameter("unqGenTipoClienteKey", typeof(System.Guid));
    
            var vchDescripcionParameter = vchDescripcion != null ?
                new ObjectParameter("vchDescripcion", vchDescripcion) :
                new ObjectParameter("vchDescripcion", typeof(string));
    
            var decDescuentoParameter = decDescuento.HasValue ?
                new ObjectParameter("decDescuento", decDescuento) :
                new ObjectParameter("decDescuento", typeof(decimal));
    
            var intTopParameter = intTop.HasValue ?
                new ObjectParameter("intTop", intTop) :
                new ObjectParameter("intTop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("prMantenimientoTipoCliente", unqGenTipoClienteKeyParameter, vchDescripcionParameter, decDescuentoParameter, intTopParameter);
        }
    
        public virtual ObjectResult<prGetComentarioXML_Result> prGetComentarioXML(string vchId, string vchSchema, string vchTabla)
        {
            var vchIdParameter = vchId != null ?
                new ObjectParameter("vchId", vchId) :
                new ObjectParameter("vchId", typeof(string));
    
            var vchSchemaParameter = vchSchema != null ?
                new ObjectParameter("vchSchema", vchSchema) :
                new ObjectParameter("vchSchema", typeof(string));
    
            var vchTablaParameter = vchTabla != null ?
                new ObjectParameter("vchTabla", vchTabla) :
                new ObjectParameter("vchTabla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetComentarioXML_Result>("prGetComentarioXML", vchIdParameter, vchSchemaParameter, vchTablaParameter);
        }
    
        public virtual int prValidaReferencias(Nullable<System.Guid> unqKey, string vchTabla, string vchSchema)
        {
            var unqKeyParameter = unqKey.HasValue ?
                new ObjectParameter("unqKey", unqKey) :
                new ObjectParameter("unqKey", typeof(System.Guid));
    
            var vchTablaParameter = vchTabla != null ?
                new ObjectParameter("vchTabla", vchTabla) :
                new ObjectParameter("vchTabla", typeof(string));
    
            var vchSchemaParameter = vchSchema != null ?
                new ObjectParameter("vchSchema", vchSchema) :
                new ObjectParameter("vchSchema", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prValidaReferencias", unqKeyParameter, vchTablaParameter, vchSchemaParameter);
        }
    
        public virtual int SetComentarioXML(Nullable<System.Guid> unqId, string vchSchema, string vchTabla, string vchUsuario, string accion, string comentario)
        {
            var unqIdParameter = unqId.HasValue ?
                new ObjectParameter("unqId", unqId) :
                new ObjectParameter("unqId", typeof(System.Guid));
    
            var vchSchemaParameter = vchSchema != null ?
                new ObjectParameter("vchSchema", vchSchema) :
                new ObjectParameter("vchSchema", typeof(string));
    
            var vchTablaParameter = vchTabla != null ?
                new ObjectParameter("vchTabla", vchTabla) :
                new ObjectParameter("vchTabla", typeof(string));
    
            var vchUsuarioParameter = vchUsuario != null ?
                new ObjectParameter("vchUsuario", vchUsuario) :
                new ObjectParameter("vchUsuario", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("Comentario", comentario) :
                new ObjectParameter("Comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetComentarioXML", unqIdParameter, vchSchemaParameter, vchTablaParameter, vchUsuarioParameter, accionParameter, comentarioParameter);
        }
    
        public virtual ObjectResult<string> GetLastFolio(string serie)
        {
            var serieParameter = serie != null ?
                new ObjectParameter("Serie", serie) :
                new ObjectParameter("Serie", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetLastFolio", serieParameter);
        }
    
        public virtual int GetNextFolio(string serie, ObjectParameter folio)
        {
            var serieParameter = serie != null ?
                new ObjectParameter("Serie", serie) :
                new ObjectParameter("Serie", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetNextFolio", serieParameter, folio);
        }
    
        public virtual ObjectResult<prGetCliente_Result> prGetCliente(Nullable<System.Guid> unqGenClienteKey)
        {
            var unqGenClienteKeyParameter = unqGenClienteKey.HasValue ?
                new ObjectParameter("unqGenClienteKey", unqGenClienteKey) :
                new ObjectParameter("unqGenClienteKey", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetCliente_Result>("prGetCliente", unqGenClienteKeyParameter);
        }
    
        public virtual ObjectResult<prGetMastCotizacion_Result> prGetMastCotizacion(Nullable<System.Guid> unqCtzMastCotizacionKey)
        {
            var unqCtzMastCotizacionKeyParameter = unqCtzMastCotizacionKey.HasValue ?
                new ObjectParameter("unqCtzMastCotizacionKey", unqCtzMastCotizacionKey) :
                new ObjectParameter("unqCtzMastCotizacionKey", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetMastCotizacion_Result>("prGetMastCotizacion", unqCtzMastCotizacionKeyParameter);
        }
    }
}
