//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGAIJE.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public System.Guid UnqGenUsuarioKey { get; set; }
        public string vchUsuario { get; set; }
        public string vchClave { get; set; }
        public bool bitActivo { get; set; }
        public string xmlHistorial { get; set; }
        public string vchConfirmarClave { get; set; }
    }
}
